# Generated by Django 2.0.4 on 2018-11-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzleName', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('gridDim', models.IntegerField(blank=True, null=True)),
                ('shapeData', models.TextField()),
                ('solutionCameraAngles', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LevelSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canPlay', models.BooleanField(default=True)),

            ],
        ),
    ]
