# Generated by Django 2.0.4 on 2018-11-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0002_remove_url_owner'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelset',
            name='urls',
            field=models.ManyToManyField(to='datacollection.URL'),
        ),
    ]
