# Generated by Django 2.0.4 on 2018-11-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_levelset_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='puzzleName',
            new_name='name',
        ),
    ]
