# Generated by Django 2.0.4 on 2018-11-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20181114_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='name',
            new_name='levelname',
        ),
        migrations.AlterField(
            model_name='level',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
