# Generated by Django 2.0.4 on 2018-05-03 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(max_length=32)),
                ('context', models.CharField(max_length=32)),
                ('params', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('local_creation_time', models.DateTimeField(null=True)),
                ('user_agent', models.CharField(max_length=200, null=True)),
                ('screen_size', models.CharField(max_length=12, null=True)),
                ('browser_url', models.CharField(max_length=200, null=True)),
                ('languages', models.CharField(max_length=50, null=True)),
                ('client_ip', models.CharField(max_length=15, null=True)),
                ('client_ip_other', models.CharField(max_length=15, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='session',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='datacollection.GameSession'),
        ),
    ]
