# Generated by Django 2.0.4 on 2018-11-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='levelsets',
            field=models.ManyToManyField(blank=True, to='games.LevelSet'),
        ),
    ]
