# Generated by Django 2.1.7 on 2019-03-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='canEdit',
        ),
        migrations.RemoveField(
            model_name='url',
            name='levelsets',
        ),
        migrations.RemoveField(
            model_name='url',
            name='useGuests',
        ),
        migrations.AddField(
            model_name='url',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
