# Generated by Django 2.0.4 on 2018-05-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='local_creation_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
