# Generated by Django 2.0.4 on 2018-05-16 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('datacollection', '0002_auto_20180503_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session'),
        ),
    ]
