# Generated by Django 2.1.3 on 2018-11-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0004_auto_20181114_1547'),
        ('datacollection', '0002_auto_20181114_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attempted',
            field=models.ManyToManyField(blank=True, related_name='levels_attempted', to='games.Level'),
        ),
        migrations.AddField(
            model_name='player',
            name='completed',
            field=models.ManyToManyField(blank=True, related_name='levels_completed', to='games.Level'),
        ),
    ]
