# Generated by Django 2.1.7 on 2019-03-25 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shadowspect', '0002_auto_20190325_0541'),
        ('datacollection', '0002_auto_20190325_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='levels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shadowspect.Level'),
        ),
    ]
