# Generated by Django 2.1.7 on 2019-03-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0003_url_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='ip',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
