# Generated by Django 2.0.4 on 2018-10-31 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0003_auto_20181031_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
