# Generated by Django 2.0.4 on 2018-05-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0003_gamesession_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='session_id',
            new_name='session',
        ),
    ]
