# Generated by Django 2.2.13 on 2020-12-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0004_auto_20190327_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datacollection.Player'),
        ),
        migrations.AlterField(
            model_name='customsession',
            name='url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datacollection.URL'),
        ),
    ]
