# Generated by Django 2.2.13 on 2021-03-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0004_auto_20190327_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='process',
            field=models.BooleanField(default=False),
        ),
    ]
