# Generated by Django 2.0.4 on 2018-11-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0005_url_levelsets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='levelsets',
        ),
    ]
