# Generated by Django 2.0.4 on 2018-07-10 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0005_auto_20180709_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session'),
        ),
    ]
