# Generated by Django 2.0.4 on 2018-07-11 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0006_auto_20180710_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='context',
        ),
    ]
