# Generated by Django 2.1.5 on 2019-02-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50, unique=True)),
                ('ingamename', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('gridDim', models.IntegerField(blank=True, null=True)),
                ('shapeData', models.TextField()),
                ('solutionCameraAngles', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LevelSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('canPlay', models.BooleanField(default=True)),
                ('levels', models.ManyToManyField(to='shadowspect.Level')),
            ],
        ),
    ]
