# Generated by Django 2.1.7 on 2019-03-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0002_auto_20190325_0541'),
        ('shadowspect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50, unique=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='levelset',
            name='levels',
        ),
        migrations.RemoveField(
            model_name='level',
            name='description',
        ),
        migrations.RemoveField(
            model_name='level',
            name='gridDim',
        ),
        migrations.RemoveField(
            model_name='level',
            name='ingamename',
        ),
        migrations.RemoveField(
            model_name='level',
            name='shapeData',
        ),
        migrations.RemoveField(
            model_name='level',
            name='solutionCameraAngles',
        ),
        migrations.AddField(
            model_name='level',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LevelSet',
        ),
    ]
