# Generated by Django 2.2.13 on 2020-08-10 22:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0004_auto_20190327_1957'),
        ('shadowspect', '0002_auto_20190325_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replay',
            old_name='data',
            new_name='replay',
        ),
        migrations.RemoveField(
            model_name='replay',
            name='filename',
        ),
        migrations.AddField(
            model_name='replay',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='replay',
            name='event_range',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='replay',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='replay',
            name='level_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shadowspect.Level'),
        ),
        migrations.AddField(
            model_name='replay',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datacollection.Player'),
        ),
        migrations.AddField(
            model_name='replay',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datacollection.URL'),
        ),
    ]
