# Generated by Django 2.1.3 on 2018-11-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shadowspect', '0003_auto_20181114_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='name',
            new_name='ingamename',
        ),
        migrations.AddField(
            model_name='level',
            name='filename',
            field=models.CharField(default='intro1', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
