# Generated by Django 2.2.13 on 2020-08-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowspect', '0004_auto_20200810_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
