# Generated by Django 2.2.13 on 2020-08-11 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shadowspect', '0005_auto_20200811_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='replay',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
