# Generated by Django 2.2.13 on 2020-08-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowspect', '0006_auto_20200811_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='replay_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
